### ISSUE TITLE
`--device cpu` seems to be ignored by dataloaders for `ketos test`

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#380]
As I launch a test while training another model and having my memory full, I ran into a  CUDA error despite using `--device cpu` on `ketos test`

```
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 34, in _pin_memory_loop
    data = pin_memory(data)
  File "env/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
    return type(data)({k: pin_memory(sample) for k, sample in data.items()})  # type: ignore[call-arg]
  File "env/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in <dictcomp>
    return type(data)({k: pin_memory(sample) for k, sample in data.items()})  # type: ignore[call-arg]
  File "env/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 50, in pin_memory
    return data.pin_memory()
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Source of the issue:

```
│ env/lib/python3.8/site-packages/kraken/ketos.py:780 in test    │
│                                                                                                  │
│    777 │   │   │   batches = len(ds_loader)                                                      │
│    778 │   │   │   pred_task = progress.add_task('Evaluating', total=batches, visible=True if n  │
│    779 │   │   │                                                                                 │
│ ❱  780 │   │   │   for batch in ds_loader:                                                       │
│    781 │   │   │   │   im = batch['image']                                                       │
│    782 │   │   │   │   text = batch['target']                                                    │
│    783 │   │   │   │   lens = batch['seq_lens']
```

And I am using an arrow file.

**Comment by mittagessen** [comment]
I assume you're talking about `segtest` as `test` doesn't have a `--device` switch. I just fixed it, there was a mistake with the device specification differences between pytorch-lightning and native pytorch. It must have crept in when I started rewriting the test commands to use ptl testing but I stopped.

**Comment by PonteIneptique** [comment]
Hmm, `test` doest have a `--device` switch, but does not use it internally:

https://github.com/mittagessen/kraken/blob/7c00184e238836a068ac54653211caad94337724/kraken/ketos.py#L646

**Comment by PonteIneptique** [comment]
Actually, looking at `ketos test`, `device` from `--device` option is never used, which is odd: https://github.com/mittagessen/kraken/blob/7c00184e238836a068ac54653211caad94337724/kraken/ketos.py#L687-L808

I feel like either nn should be set to `device` (like for segtest) or the dataloader ? (But I think pytorch-lightning does not need the dataloader to changed)

**Comment by mittagessen** [comment]
I just fixed it. The `TorchSeqRecognizer` takes care of moving the tensors to the correct device but it needs to be told which one it is which was missing. I couldn't really reproduce your CUDA allocation problem but I suspect it is related to some recent DataLoader memory pinning changes which look like they might do shenanigans like that.

**Comment by PonteIneptique** [comment]
> I couldn't really reproduce your CUDA allocation problem but I suspect it is related to some recent DataLoader memory pinning changes which look like they might do shenanigans like that.

I heavily suspect that because I was training and taking 90% of the GPU RAM capacity, and because torch lightning kinda default to using GPU (if memory serves me well ?), when I tried to test, it went to the GPU which was already full.

**Comment by mittagessen** [comment]
On 22/08/24 10:41PM, Thibault Clérice wrote:
> I heavily suspect that because I was training and taking 90% of the
> GPU RAM capacity, and because torch lightning kinda default to using
> GPU (if memory serves me well ?), when I tried to test, it went to the
> GPU which was already full.

The testing code doesn't use lightning at all.

**Comment by PonteIneptique** [comment]
Then I don't know :)
