### ISSUE TITLE
Kraken==4.2.0 doesn't work with RTX 3060

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#386]
Hi @PonteIneptique @mittagessen, 

This is not a continuation of #385 as I was able to solve by adding ```--normalization``` in my command. 

I updated (again: it didn't work the last time as well) to ```4.2.0``` upon @PonteIneptique 's recommendation, and found that my card is not compatible: 

```
Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
WARNING:py.warnings:/home/rohan/codes/kraken/venv/lib/python3.8/site-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA GeForce RTX 3060 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3060 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
``` 
PyTorch in ```4.2.0``` was ```1.11.0```. 

I even tried the script in #309 but it didn't help, although it works in ```4.1.2```.

So I reverted back to ```4.1.2```, used the script in #309, and was able to start training with no errors. 

Not sure what exactly I should do to use ```4.2.0```, so posting this here. 

I am also attaching a text file where I've pasted the terminal output of these steps.
[kraken4.2.txt](https://github.com/mittagessen/kraken/files/9633495/kraken4.2.txt)

**Comment by rohanchn** [comment]
Yep, I have incompatible cuda: ```11.7```
I tried with this link earlier in my envrionment, and it doesn't work for me. Somehow ```4.1.2``` is working for me. 
I'll give it a try again in some time.
